### ISSUE TITLE
Hope to get more details

### ISSUE THREAD

**Issue by fys666** [Zaoqu-Liu/IRLS#1]
Hi, I am very interested in your literature, especially the integrated machine learning part. I also want to reproduce it to complete my graduation dissertation, but after watching your code base, I found that some input files are not provided.What a pity! I can't know the input format, so I am writing this letter hoping to get the model-step.Rda file.If it would be convenient , please send the file to my email 1432618546@qq.com!
Of courese.Whether you want to share or not, still thank you very much for your selfless and generous code

**Comment by Ethan-Fu-2000** [comment]
> Hi, I am very interested in your literature, especially the integrated machine learning part. I also want to reproduce it to complete my graduation dissertation, but after watching your code base, I found that some input files are not provided.What a pity! I can't know the input format, so I am writing this letter hoping to get the model-step.Rda file.If it would be convenient , please send the file to my email [1432618546@qq.com](mailto:1432618546@qq.com)! Of courese.Whether you want to share or not, still thank you very much for your selfless and generous code

If the data is confidential, you can consider giving me the data format, or you can delete some important data, please, this is really helpful for me

**Comment by fys666** [comment]
> Hi, I am very interested in your literature, especially the integrated machine learning part. I also want to reproduce it to complete my graduation dissertation, but after watching your code base, I found that some input files are not provided.What a pity! I can't know the input format, so I am writing this letter hoping to get the model-step.Rda file.If it would be convenient , please send the file to my email [1432618546@qq.com](mailto:1432618546@qq.com)! Of courese.Whether you want to share or not, still thank you very much for your selfless and generous code

If the data is confidential, you can consider giving me the data format, or you can delete some important data, please, this is really helpful to me

**Comment by qitongxu** [comment]
Hi, I am very interested in your literature, especially the integrated machine learning part. I also want to reproduce it to complete my graduation dissertation, but after watching your code base, I found that some input files are not provided.What a pity! I can't know the input format, so I am writing this letter hoping to get the model-step.Rda file.If it would be convenient , please send the file to my email [879604721@qq.com](mailto:879604721@qq.com)! Of courese.Whether you want to share or not, still thank you very much for your selfless and generous code

If the data is confidential, you can consider giving me the data format, or you can delete some important data, please, this is really helpful for me

**Comment by Ethan-Fu-2000** [comment]
> Hi, I am very interested in your literature, especially the integrated machine learning part. I also want to reproduce it to complete my graduation dissertation, but after watching your code base, I found that some input files are not provided.What a pity! I can't know the input format, so I am writing this letter hoping to get the model-step.Rda file.If it would be convenient , please send the file to my email [879604721@qq.com](mailto:879604721@qq.com)! Of courese.Whether you want to share or not, still thank you very much for your selfless and generous code
> 
> If the data is confidential, you can consider giving me the data format, or you can delete some important data, please, this is really helpful for me

Is it helpful for you to plagiarize my words? You will never get the code.Never!
