### ISSUE TITLE
data lost

### ISSUE THREAD

**Issue by saisaitian** [Zaoqu-Liu/IRLS#2]
could  you share the ‘all-signature.rda'， ‘TCGA.rda’ and ‘model-step.Rda’，so that we can run it well?

**Comment by biadarola** [comment]
Hello, 

I agree, if it is possible could you share this data or at least explain how the data should be formatted?

Thank you very much!

**Comment by DocMonster77** [comment]
could you share the ‘all-signature.rda'， ‘TCGA.rda’ and ‘model-step.Rda’?

**Comment by momoGWAS** [comment]
could you share the ‘all-signature.rda'， ‘TCGA.rda’ and ‘model-step.Rda’? i need this ,thank you very much, god bless you

**Comment by momoGWAS** [comment]
> could you share the ‘all-signature.rda'， ‘TCGA.rda’ and ‘model-step.Rda’，so that we can run it well?

i need it too,could you please share me,thanks a lot
