### ISSUE TITLE
Hope to know exact regression coefficients

### ISSUE THREAD

**Issue by luanshifusheng91** [Zaoqu-Liu/IRLS#4]
Hi, I am very interested in your literature.  We are doing similar work and hope to compare the performance of signatures have been developed, include yours. However, we donnot know exact regression coefficients of 16 lncRNA in your model (Fig. 2C of your literature).
If it is possible could you share this data? Whether you want to share or not, still thank you very much.

**Comment by Zaoqu-Liu** [comment]
加我微信liuzaoqu


| |
Zaoqu Liu
***@***.***
Zhengzhou University
|


---- Replied Message ----
| From | ***@***.***> |
| Date | 02/6/2023 23:40 |
| To | ***@***.***> |
| Cc | ***@***.***> |
| Subject | [Zaoqu-Liu/IRLS] Hope to know exact regression coefficients (Issue #4) |

Hi, I am very interested in your literature. We are doing similar work and hope to compare the performance of signatures have been developed, include yours. However, we donnot know exact regression coefficients of 16 lncRNA in your model (Fig. 2C of your literature).
If it is possible could you share this data? Whether you want to share or not, still thank you very much.
