### ISSUE TITLE
Question about model integration

### ISSUE THREAD

**Issue by hxlei** [Zaoqu-Liu/IRLS#5]
Thanks for the great work first, which inspired me a lot. I read methods and supplementary methods. However I find little information about integration steps of two models. I notice there are only codes with "StepCox+survival-svm" in "Machine Learning based intergration.R",  under the title "3-8.StepCox+gbm", which makes me confused. Would you like to share more details about how to integrate two models, such as RSF+Enet , coxBoost + survival-SVM ? Thank you very much for sharing.

**Comment by oujjNJ** [comment]
Dear author, 

I also have a little problem about the integration of two ML models. It seems that, the codes with "StepCox+survivalsvm" in your R script "Machine Learning based intergration.R" only showed the StepCox step. 
Would you like to share more details about how to integrate two models ? 

Thanks!
