### ISSUE TITLE
could you please share me 'all-signature rda', you are my hero

### ISSUE THREAD

**Issue by momoGWAS** [Zaoqu-Liu/IRLS#7]
my email
dr_liuxianqiang@163.com

**Comment by momoGWAS** [comment]
Hi, I am very very interested in your literature, especially the integrated machine learning part. It is surprising for me.  Of courese.Whether you want to share or not, still thank you very much for your selfless and generous code

If the data is confidential, you can consider giving me the data format, or you can delete some important data, please, this is really really helpful for me! Thank you very much!

**Comment by Zaoqu-Liu** [comment]
加一下我微信liuzaoqu


| |
Zaoqu Liu
Doctor
|
|
18439932426
***@***.***
Peking Union Medical College
|


---- Replied Message ----
| From | ***@***.***> |
| Date | 12/25/2023 21:32 |
| To | ***@***.***> |
| Cc | ***@***.***> |
| Subject | Re: [Zaoqu-Liu/IRLS] could you please share me 'all-signature rda', you are my hero (Issue #7) |

Hi, I am very very interested in your literature, especially the integrated machine learning part. It is surprising for me. Of courese.Whether you want to share or not, still thank you very much for your selfless and generous code

If the data is confidential, you can consider giving me the data format, or you can delete some important data, please, this is really really helpful for me! Thank you very much!

**Comment by 123wanguang123456** [comment]
@drliu-SWMU @Zaoqu-Liu You are my hero. I am extremely interested in the "all-signature RDA" data. Could you please share the format of this data with me? It would be of great help to me. My email address is: [2836683219@qq.com]
